name: Cypress Automation

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm install -g npm
        npm install

    - name: Install Cypress and Mochawesome
      run: |
        chmod +x ./node_modules/.bin/cypress
        npx cypress install
        npm install mochawesome --save-dev

    - name: Run Cypress tests with Mochawesome
      continue-on-error: true # Permite continuar incluso si hay fallos
      run: |
        npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/reports,reportFilename=results,overwrite=true,json=true,html=false"

    - name: Inspect results.json
      run: |
        if [ -f cypress/reports/results.json ]; then
          echo "Contenido de cypress/reports/results.json:"
          cat cypress/reports/results.json
        else
          echo "cypress/reports/results.json no encontrado."
        fi

    - name: Validate JSON
      run: |
        if [ -f cypress/reports/results.json ]; then
          jq empty cypress/reports/results.json && echo "JSON válido." || echo "JSON no válido."
        else
          echo "cypress/reports/results.json no encontrado."
        fi

    - name: Send results to Make
      if: always()
      env:
        MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
      run: |
        if [ -f cypress/reports/results.json ]; then
          cat cypress/reports/results.json | jq . > cleaned_results.json
          curl -L -X POST -H "Content-Type: application/json" -d @cleaned_results.json $MAKE_WEBHOOK_URL
        else
          echo "No se generaron resultados para enviar a Make."
        fi
