name: Cypress Automation

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repositorio con profundidad 1 para acelerar la descarga
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Optimización: Solo descargar la última versión

    # 2. Configuración de Node.js con cache automático
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'  # Optimización: Habilita cache automático para npm

    # 3. Cache de módulos de Node.js
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # 4. Instalación de dependencias
    - name: Install dependencies
      run: |
        npm install -g npm
        npm install

    # 5. Instalación de Cypress con permisos correctos
    - name: Install Cypress
      run: |
        chmod -R 777 ./node_modules/.bin/
        npx cypress install --force

    # 6. Ejecución de pruebas con Cypress
    - name: Run Cypress tests
      run: npx cypress run --reporter json --reporter-options toConsole=true | tee results.json

    # 7. Verificar versión de OpenSSL en GitHub Actions
    - name: Check OpenSSL Version
      run: openssl version

    # 8. Actualizar OpenSSL si es necesario
    - name: Update OpenSSL
      run: sudo apt-get install --only-upgrade openssl

    # 9. Enviar resultados por correo electrónico mediante Gmail SMTP
    - name: Send email with test results using Gmail
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465  # Cambiar a SSL en lugar de TLS
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "[Cypress] Resultados de pruebas"
        body: |
          Hola,

          Se adjuntan los resultados de las pruebas Cypress ejecutadas en GitHub Actions.
          Revisa el archivo adjunto para más detalles.

        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: ${{ secrets.EMAIL_USERNAME }}
        attachments: results.json
        secure: false  # Cambiado a false para usar SSL en el puerto 465
        ignore_cert: true  # Ignorar posibles problemas con certificados

