name: Cypress Automation

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
          export DISPLAY=:99

      - name: Run Cypress tests
        run: npx cypress run --reporter json --reporter-options toConsole=true | tee results.json

      - name: Inspect results.json
        run: |
          if [ -f results.json ]; then
            cat results.json
          else
            echo "results.json no encontrado."
          fi

      - name: Debug Webhook URL
        run: |
          curl -I ${{ secrets.MAKE_WEBHOOK_URL }}

      - name: Send results to Make on failure
        if: failure()
        env:
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
        run: |
          if [ -f results.json ]; then
            curl -L -X POST -H "Content-Type: application/json" -d @results.json $MAKE_WEBHOOK_URL
          else
            echo "Archivo results.json no encontrado. Nada que enviar."
          fi


        


    
