name: Cypress Automation

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Asegúrate de usar una versión compatible con Cypress

    - name: Install dependencies
      run: npm install

    - name: Install Cypress
      run: npx cypress install

    - name: Run Cypress tests
      run: npx cypress run --reporter json --reporter-options toConsole=true | tee results.json

    - name: Send results to Make
      if: failure()
      run: curl -X POST -H "Content-Type: application/json" -d @results.json ${{ secrets.MAKE_WEBHOOK_URL }}
