name: Cypress Automation

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm install -g npm
        npm install

    - name: Start application server
      run: |
        npm run start &
        sleep 10

    - name: Install dependencies for Cypress
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev \
            libnotify-dev libgconf-2-4 libnss3 xvfb

    - name: Install Cypress
      run: |
        chmod +x ./node_modules/.bin/cypress
        npx cypress install

    - name: Run Cypress tests
      continue-on-error: true
      run: |
        xvfb-run -a npx cypress run --reporter json --reporter-options "outputFile=results.json"

    - name: Send results to Make
      if: always()
      env:
        MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
      run: |
        if [ -f results.json ]; then
          cat results.json | jq . > cleaned_results.json
          curl -L -X POST -H "Content-Type: application/json" -d @cleaned_results.json $MAKE_WEBHOOK_URL
        else
          echo "No se generaron resultados para enviar a Make."
        fi



