name: Cypress Automation

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Cypress
      run: npx cypress install --force

    - name: Run Cypress tests
      run: npx cypress run --reporter json --reporter-options toConsole=true | tee results.json

    - name: Send email with results
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Cypress Test Results
        body: |
          Los resultados de las pruebas están adjuntos. Revisa el archivo para más detalles.
        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: ${{ secrets.EMAIL_USERNAME }}
        attachments: results.json
